<?php

declare(strict_types=1);

namespace Jcf\BoostForKiro\Steering;

use Composer\InstalledVersions;
use Illuminate\Container\Container;
use Illuminate\Support\Str;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Prompt;

class PromptToSteeringConverter
{
    /**
     * Determine whether the prompt can be represented as a static Kiro
     * manual steering file.
     */
    public function supports(Prompt $prompt): bool
    {
        return $prompt->arguments() === [];
    }

    /**
     * Convert a Prompt instance into a Kiro manual steering markdown file.
     *
     * Manual steering files are invoked on demand via `/<filename>` slash
     * commands or `#<filename>` references in chat, replacing the legacy
     * `userTriggered` Agent Hooks from Kiro 0.x.
     *
     * @see https://kiro.dev/docs/steering/#manual-inclusion
     */
    public function convert(Prompt $prompt): string
    {
        $title = 'Boost: '.Str::headline($prompt->name());
        $body = trim($this->renderPromptContent($prompt));
        $version = $this->getBoostVersion();
        $name = $prompt->name();

        return <<<MARKDOWN
---
inclusion: manual
---

<!-- Generated by jcf/boost-for-kiro-ide from laravel/boost v{$version} prompt "{$name}". Regenerate with `php artisan boost:kiro-hooks`. -->

# {$title}

{$body}
MARKDOWN;
    }

    protected function renderPromptContent(Prompt $prompt): string
    {
        /** @var Response $response */
        $response = Container::getInstance()->call([$prompt, 'handle']);

        return (string) $response->content();
    }

    protected function getBoostVersion(): string
    {
        if (InstalledVersions::isInstalled('laravel/boost')) {
            $version = InstalledVersions::getPrettyVersion('laravel/boost') ?? '0.0.0';

            return ltrim($version, 'v');
        }

        return '0.0.0';
    }
}
